#ifndef _AIRYYXX_LL_H_
#define _AIRYYXX_LL_H_
/* LL raised several warnings, ignore them */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#ifdef __cplusplus
  #pragma GCC diagnostic ignored "-Wregister"
#endif

/* Include Low Layers drivers */
#include "airyyxx_ll_adc.h"
#include "airyyxx_ll_bdma.h"
#include "airyyxx_ll_bus.h"
#include "airyyxx_ll_comp.h"
#include "airyyxx_ll_cordic.h"
#include "airyyxx_ll_cortex.h"
#include "airyyxx_ll_crc.h"
#include "airyyxx_ll_crs.h"
#include "airyyxx_ll_dac.h"
#include "airyyxx_ll_dcache.h"
#include "airyyxx_ll_delayblock.h"
#include "airyyxx_ll_dlyb.h"
#include "airyyxx_ll_dma.h"
#include "airyyxx_ll_dma2d.h"
#include "airyyxx_ll_dmamux.h"
#include "airyyxx_ll_exti.h"
#include "airyyxx_ll_fmac.h"
#include "airyyxx_ll_fmc.h"
#include "airyyxx_ll_fmpi2c.h"
#include "airyyxx_ll_fsmc.h"
#include "airyyxx_ll_gpio.h"
#include "airyyxx_ll_hrtim.h"
#include "airyyxx_ll_hsem.h"
#include "airyyxx_ll_i2c.h"
#include "airyyxx_ll_icache.h"
#include "airyyxx_ll_ipcc.h"
#include "airyyxx_ll_iwdg.h"
#include "airyyxx_ll_lpgpio.h"
#include "airyyxx_ll_lptim.h"
#include "airyyxx_ll_lpuart.h"
#include "airyyxx_ll_mdma.h"
#include "airyyxx_ll_opamp.h"
#include "airyyxx_ll_pka.h"
#include "airyyxx_ll_pwr.h"
#include "airyyxx_ll_rcc.h"
#include "airyyxx_ll_rng.h"
#include "airyyxx_ll_rtc.h"
#include "airyyxx_ll_sdmmc.h"
#include "airyyxx_ll_spi.h"
#include "airyyxx_ll_swpmi.h"
#include "airyyxx_ll_system.h"
#include "airyyxx_ll_tim.h"
#include "airyyxx_ll_ucpd.h"
#include "airyyxx_ll_usart.h"
#include "airyyxx_ll_usb.h"
#include "airyyxx_ll_utils.h"
#include "airyyxx_ll_wwdg.h"
#pragma GCC diagnostic pop
#endif /* _AIRYYXX_LL_H_ */
