name: "\U0001F41E 上报bug / Bug report"
description: "提交bug以让改进软件功能 / Create a report to help us improve"
labels: ["待分类"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你上报新的问题！ / Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: 描述一下这个bug / Describe the bug
      description: 请使用简介并详细的语句，来描述这个bug。 / A clear and concise description of what the bug is.
      placeholder: 我准备……我想要……但是实际上它……了 / I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 复现步骤 / To Reproduce
      description: 按照下面的步骤，可以复现bug / Steps to reproduce the behavior
      placeholder: 首先……然后……接着…… / Go to '...', Click on '....', Scroll down to '....'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 预期的行为 / Expected behavior
      description: 清楚简洁地描述你希望发生的事情。 / A clear and concise description of what you expected to happen.
      placeholder: 它应该…… / It should be...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 截图 / Screenshots
      description: 如果需要，请放上你的截图。 / If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: 日志 / Logs
      description: 日志贴到这里 / Upload your log files.
      description: |
        请使用```进行包裹！像下面这样

        ````
        12321312321312
        1232131232131231
        ```
    validations:
      required: false
  - type: input
    id: system
    attributes:
      label: 系统 / System
      placeholder: Win10 22H2 / Ubuntu 22.04
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: 软件版本 / Version
      placeholder: 1.0.1.1
    validations:
      required: true

  - type: checkboxes
    id: checkboxes
    attributes:
      label: 验证
      description: 提交前请确认已经做过以下操作 / Before submitting the issue, please make sure you do the following
      options:
        - label: 检查该问题是否已被提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
          required: true
        - label: 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
