#define USE_HAL_DRIVER

#ifdef AIRC0xx
  #include "system_air001c0xx.c"
#elif AIR001xx
  #include "system_air001xx.c"
#elif AIRF1xx
  #include "system_air001f1xx.c"
#elif AIRF2xx
  #include "system_air001f2xx.c"
#elif AIRF3xx
  #include "system_air001f3xx.c"
#elif AIRF4xx
  #include "system_air001f4xx.c"
#elif AIRF7xx
  #include "system_air001f7xx.c"
#elif AIRG0xx
  #include "system_air001g0xx.c"
#elif AIRG4xx
  #include "system_air001g4xx.c"
#elif AIRH7xx
  #include "system_air001h7xx.c"
#elif AIRL0xx
  #include "system_air001l0xx.c"
#elif AIRL1xx
  #include "system_air001l1xx.c"
#elif AIRL4xx
  #include "system_air001l4xx.c"
#elif AIRL5xx
  #include "system_air001l5xx_ns.c"
#elif AIRMP1xx
  #include "system_air001mp1xx.c"
#elif AIRU5xx
  #include "system_air001u5xx.c"
#elif AIRWBxx
  #include "system_air001wbxx.c"
#elif AIRWLxx
  #include "system_air001wlxx.c"
#endif
