name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: source
          submodules: true

      - name: Remove git information from destination repository
        run: |
          mkdir dest.git
          cp -r source/* dest.git/
          cd dest.git
          rm -rf .git
      
      - name: Zip folder and save
        run: |
          mkdir -p Arduino-AirMCU
          cp -r dest.git/* Arduino-AirMCU/
          zip -r AirMCU-${GITHUB_REF#refs/tags/}.zip Arduino-AirMCU

      - name: Send repository_dispatch event to package json
        run: |
          curl -X POST https://api.github.com/repos/Air-duino/Arduino-AirMCU/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.USER_TOKEN }} \
          --data '{"event_type": "AirMCU"}'

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true