name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: source

      - name: Create bare clone and push to destination repository
        run: |
          git clone --bare source dest.git
          cd dest.git
          git push --mirror https://<username>:${{ secrets.API_TOKEN_GITHUB }}@github.com/<org>/<dest_repo>.git
      
      - name: Remove git information from destination repository
        run: |
          cd dest.git
          rm -rf .git
      
      - name: Zip folder and save
        run: |
          mkdir -p Arduino-AirMCU
          cp -r dest.git/* Arduino-AirMCU/
          zip -r AirMCU-${GITHUB_REF#refs/tags/}.zip Arduino-AirMCU
          ls -a

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true